/**
 * Passive-tree artwork, from Grinding Gear Games' own export.
 *
 * `packages/data/tree-art/` is generated by scripts/fetch-tree-assets.mjs and
 * carries four texture atlases plus two derived JSON indexes. The art is
 * (c) Grinding Gear Games and is redistributed under their third-party policy
 * for non-commercial fan tools; see the attribution note in README.
 *
 * The atlases are stored at half size (`scale: 0.5` in the atlas meta), and the
 * tree's coordinates are in the original art's space, so every size the
 * renderer draws at is `atlasRect / scale`. Those sizes are precomputed in
 * `draw` / `drawFrame` so no component has to know about the convention.
 */
import indexJson from '@poe2coach/data/tree-art/index.json'
import geometryJson from '@poe2coach/data/tree-art/geometry.json'
import frameUrl from '@poe2coach/data/tree-art/frame.webp'
import lineUrl from '@poe2coach/data/tree-art/line.webp'
import skillsDisabledUrl from '@poe2coach/data/tree-art/skills-disabled.webp'
import skillsUrl from '@poe2coach/data/tree-art/skills.webp'

export interface Rect {
  x: number
  y: number
  w: number
  h: number
}

/** Where one of a node's two states lives: the atlas, and the rect inside it. */
export interface IconStateRects {
  /** From the `skills` atlas. */
  allocated: Rect | null
  /** From the `skills-disabled` atlas. */
  unallocated: Rect | null
}

interface AtlasMeta {
  image: string
  scale: number
  width: number
  height: number
}

export interface TreeArtIndex {
  atlases: Record<string, AtlasMeta>
  /** Node kind -> the size to draw its icon at, in tree coordinates. */
  draw: Record<string, number>
  /** `<kind>.<state>` -> the size to draw its frame at, in tree coordinates. */
  drawFrame: Record<string, number>
  /** `<kind>.<state>` -> rect, where kind also covers ascendancy variants. */
  frames: Record<string, Rect>
  /** Line-art rects by their atlas name with the `line:` prefix stripped. */
  lines: Record<string, Rect>
  /**
   * Our tree.json's exact `icon` string (still `.dds`) -> rects per node kind.
   * A path can be listed under several kinds; the renderer picks by the node's
   * own kind. Mastery nodes are absent — their art lives in a separate atlas
   * this build does not ship, so they draw as a bare frame.
   */
  nodes: Record<string, Record<string, IconStateRects>>
}

export interface TreeGeometry {
  /** Node id -> absolute [x, y], in the same space as the artwork. */
  positions: Record<string, [number, number]>
  /** Official connection list, as id strings. */
  edges: [string, string][]
}

export const TREE_ART_INDEX = indexJson as unknown as TreeArtIndex
export const TREE_GEOMETRY = geometryJson as unknown as TreeGeometry

let edgesCache: [number, number][] | null = null

/**
 * The tree's graph as numeric pairs, for callers that need to walk it.
 *
 * This is GGG's own edge list rather than `node.connections`, which only
 * carries part of the real graph — a walk over `connections` alone reaches 3
 * main-tree nodes from a class start where this reaches 7.
 */
export function treeEdges(): [number, number][] {
  if (!edgesCache) edgesCache = TREE_GEOMETRY.edges.map(([a, b]) => [Number(a), Number(b)])
  return edgesCache
}

/** Atlas name -> the module URL Vite emitted for it. */
const SOURCES: Record<string, string> = {
  skills: skillsUrl,
  'skills-disabled': skillsDisabledUrl,
  frame: frameUrl,
  line: lineUrl,
}

export interface TreeArt {
  index: TreeArtIndex
  geometry: TreeGeometry
  /** Decoded atlases, keyed the same way as `index.atlases`. */
  images: Record<string, CanvasImageSource>
}

function loadImage(url: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const image = new Image()
    image.onload = () => resolve(image)
    image.onerror = () => reject(new Error(`tree art failed to load: ${url}`))
    image.src = url
  })
}

let pending: Promise<TreeArt> | null = null

/**
 * Decode every atlas once. Drawing has to wait on this: `drawImage` silently
 * draws nothing for an image that has not finished decoding, so the canvas
 * awaits this before its first paint.
 */
export function loadTreeArt(): Promise<TreeArt> {
  if (pending) return pending
  pending = (async () => {
    const names = Object.keys(SOURCES)
    const loaded = await Promise.all(names.map((name) => loadImage(SOURCES[name])))
    const images: Record<string, CanvasImageSource> = {}
    names.forEach((name, i) => (images[name] = loaded[i]))
    return { index: TREE_ART_INDEX, geometry: TREE_GEOMETRY, images }
  })()
  return pending
}
