/**
 * Passive-tree artwork, from Grinding Gear Games' own export.
 *
 * `packages/data/tree-art/` is generated by scripts/fetch-tree-assets.mjs and
 * carries four texture atlases plus two derived JSON indexes. The art is
 * (c) Grinding Gear Games and is redistributed under their third-party policy
 * for non-commercial fan tools; see the attribution note in README.
 *
 * The atlases are stored at half size (`scale: 0.5` in the atlas meta), and the
 * tree's coordinates are in the original art's space, so every size the
 * renderer draws at is `atlasRect / scale`. Those sizes are precomputed in
 * `draw` / `drawFrame` so no component has to know about the convention.
 */
import indexJson from '@poe2coach/data/tree-art/index.json'
import geometryJson from '@poe2coach/data/tree-art/geometry.json'
import frameUrl from '@poe2coach/data/tree-art/frame.webp'
import groupBackgroundUrl from '@poe2coach/data/tree-art/group-background.webp'
import masteryActiveUrl from '@poe2coach/data/tree-art/mastery-effect-active.webp'
import lineUrl from '@poe2coach/data/tree-art/line.webp'
import skillsDisabledUrl from '@poe2coach/data/tree-art/skills-disabled.webp'
import skillsUrl from '@poe2coach/data/tree-art/skills.webp'

export interface Rect {
  x: number
  y: number
  w: number
  h: number
}

/** Where one of a node's two states lives: the atlas, and the rect inside it. */
export interface IconStateRects {
  /** From the `skills` atlas. */
  allocated: Rect | null
  /** From the `skills-disabled` atlas. */
  unallocated: Rect | null
}

interface AtlasMeta {
  image: string
  scale: number
  width: number
  height: number
}

export interface TreeArtIndex {
  atlases: Record<string, AtlasMeta>
  /** Node kind -> the size to draw its icon at, in tree coordinates. */
  draw: Record<string, number>
  /** `<kind>.<state>` -> the size to draw its frame at, in tree coordinates. */
  drawFrame: Record<string, number>
  /** `<kind>.<state>` -> rect, where kind also covers ascendancy variants. */
  frames: Record<string, Rect>
  /** Line-art rects by their atlas name with the `line:` prefix stripped. */
  lines: Record<string, Rect>
  /**
   * The disc an ascendancy cluster sits on once it is moved into the main
   * tree's empty centre. Shipped 4000 units across, which is wider than that
   * space, so the renderer sizes it to the hole instead of using the art's own
   * width.
   */
  groups: Record<string, Rect>
  /**
   * Mastery nodes have no entry in `nodes`; their plate is keyed by the node's
   * `activeEffectImage`. The atlas is authored far larger than a node (488 tree
   * units against a 102-unit frame), so it is drawn at the frame's size rather
   * than its own — it is a high-resolution pattern, not a big node.
   *
   * Only the lit set is packaged, so an unallocated mastery is drawn from it at
   * reduced opacity.
   */
  masteries: Record<string, Rect>
  /**
   * Our tree.json's exact `icon` string (still `.dds`) -> rects per node kind.
   * A path can be listed under several kinds; the renderer picks by the node's
   * own kind. Mastery nodes are absent — their art lives in a separate atlas
   * this build does not ship, so they draw as a bare frame.
   */
  nodes: Record<string, Record<string, IconStateRects>>
}

export type RawEdge = [string, string] | [string, string, number, number, number]

export interface TreeGeometry {
  /** Node id -> absolute [x, y], in the same space as the artwork. */
  positions: Record<string, [number, number]>
  /** Official connection list, as id strings (with optional orbit, orbitX, orbitY for arcs). */
  edges: RawEdge[]
  /** Group id -> its centre. Orbit rings are concentric about this point. */
  groups: Record<string, [number, number]>
}

export const TREE_ART_INDEX = indexJson as unknown as TreeArtIndex
export const TREE_GEOMETRY = geometryJson as unknown as TreeGeometry

let edgesCache: [number, number][] | null = null

/**
 * The tree's graph as numeric pairs, for callers that need to walk it.
 *
 * This is GGG's own edge list rather than `node.connections`, which only
 * carries part of the real graph — a walk over `connections` alone reaches 3
 * main-tree nodes from a class start where this reaches 7.
 */
export function treeEdges(): [number, number][] {
  if (!edgesCache) edgesCache = TREE_GEOMETRY.edges.map(([a, b]) => [Number(a), Number(b)])
  return edgesCache
}

/** Atlas name -> the module URL Vite emitted for it. */
const SOURCES: Record<string, string> = {
  skills: skillsUrl,
  'skills-disabled': skillsDisabledUrl,
  frame: frameUrl,
  line: lineUrl,
  'group-background': groupBackgroundUrl,
  'mastery-effect-active': masteryActiveUrl,
}

export interface TreeArt {
  index: TreeArtIndex
  geometry: TreeGeometry
  /** Decoded atlases, keyed the same way as `index.atlases`. */
  images: Record<string, CanvasImageSource>
  /**
   * `<kind>.<state>` -> the diameter a node's icon may occupy, in tree units.
   *
   * `index.draw` is the icon art's *own* size, which is roughly twice the clear
   * aperture inside its frame — measured, a normal node's ring has a 50-unit
   * hole against a 68-unit icon — so drawing at that size pushes the icon out
   * through the ring. These are measured off the frame art instead of assumed,
   * so they follow the art if it changes.
   */
  iconInset: Record<string, number>
}

/**
 * Below this fraction of the rays the frame is treated as solid, so decorative
 * protrusions on a frame do not shrink its aperture to nothing.
 */
const APERTURE_PERCENTILE = 0.1

/**
 * The radius of the clear hole in the middle of a frame, in atlas pixels:
 * walk outward along many rays and take the distance at which the art first
 * becomes opaque.
 */
function apertureRadius(image: CanvasImageSource, rect: Rect): number {
  const canvas = document.createElement('canvas')
  canvas.width = rect.w
  canvas.height = rect.h
  const ctx = canvas.getContext('2d')
  if (!ctx) return 0
  ctx.drawImage(image, rect.x, rect.y, rect.w, rect.h, 0, 0, rect.w, rect.h)
  const { data } = ctx.getImageData(0, 0, rect.w, rect.h)
  const cx = rect.w / 2
  const cy = rect.h / 2
  const hits: number[] = []
  for (let angle = 0; angle < 360; angle += 2) {
    const rad = (angle * Math.PI) / 180
    let d = 0
    for (; d < Math.min(cx, cy); d += 0.5) {
      const x = Math.round(cx + Math.cos(rad) * d)
      const y = Math.round(cy + Math.sin(rad) * d)
      if (data[(y * rect.w + x) * 4 + 3] > 24) break
    }
    hits.push(d)
  }
  hits.sort((a, b) => a - b)
  return hits[Math.floor(hits.length * APERTURE_PERCENTILE)] ?? 0
}

function loadImage(url: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const image = new Image()
    image.onload = () => resolve(image)
    image.onerror = () => reject(new Error(`tree art failed to load: ${url}`))
    image.src = url
  })
}

let pending: Promise<TreeArt> | null = null

/**
 * Decode every atlas once. Drawing has to wait on this: `drawImage` silently
 * draws nothing for an image that has not finished decoding, so the canvas
 * awaits this before its first paint.
 */
export function loadTreeArt(): Promise<TreeArt> {
  if (pending) return pending
  pending = (async () => {
    const names = Object.keys(SOURCES)
    const loaded = await Promise.all(names.map((name) => loadImage(SOURCES[name])))
    const images: Record<string, CanvasImageSource> = {}
    names.forEach((name, i) => (images[name] = loaded[i]))

    const frameImage = images.frame
    const frameScale = TREE_ART_INDEX.atlases.frame.scale
    const iconInset: Record<string, number> = {}
    for (const [key, rect] of Object.entries(TREE_ART_INDEX.frames)) {
      if (!frameImage) continue
      const radius = apertureRadius(frameImage, rect)
      if (radius > 0) iconInset[key] = (radius * 2) / frameScale
    }

    return { index: TREE_ART_INDEX, geometry: TREE_GEOMETRY, images, iconInset }
  })()
  return pending
}
