// Generated by scripts/fetch-atlas-sprites.mjs -- do not edit.
// PoE2 atlas node icons and frame art, cropped from the Maxroll planner sprite
// bundle (datamined game art, (c) GGG). Keys are lowercase art basenames.
import _i_atlasmasterygeneric from './icons/atlasmasterygeneric.webp'
import _i_atlasmasteryessence from './icons/atlasmasteryessence.webp'
import _i_atlasmasterybiome from './icons/atlasmasterybiome.webp'
import _i_atlasmasterystonecircles from './icons/atlasmasterystonecircles.webp'
import _i_atlasmasteryrogueexile from './icons/atlasmasteryrogueexile.webp'
import _i_atlasmasterystrongbox from './icons/atlasmasterystrongbox.webp'
import _i_atlasmasteryazmerispirits from './icons/atlasmasteryazmerispirits.webp'
import _i_atlasmasteryshrine from './icons/atlasmasteryshrine.webp'
import _i_expeditionnotable5 from './icons/expeditionnotable5.webp'
import _i_expeditionnotable3 from './icons/expeditionnotable3.webp'
import _i_strongboxnotable1 from './icons/strongboxnotable1.webp'
import _i_abyssnotable1 from './icons/abyssnotable1.webp'
import _i_disablingmasteralva from './icons/disablingmasteralva.webp'
import _i_anarchynotable3 from './icons/anarchynotable3.webp'
import _i_raremonstersnode from './icons/raremonstersnode.webp'
import _i_alvanotable4 from './icons/alvanotable4.webp'
import _i_deliriumnotable3 from './icons/deliriumnotable3.webp'
import _i_strongboxnotable3 from './icons/strongboxnotable3.webp'
import _i_exceptionalitemsboots from './icons/exceptionalitemsboots.webp'
import _i_abyssnotable4 from './icons/abyssnotable4.webp'
import _i_abysscrack from './icons/abysscrack.webp'
import _i_shrines from './icons/shrines.webp'
import _i_exceptionalitemsgloves from './icons/exceptionalitemsgloves.webp'
import _i_alvanotable3 from './icons/alvanotable3.webp'
import _i_alvanotable1 from './icons/alvanotable1.webp'
import _i_bossnotabledropmoreitems from './icons/bossnotabledropmoreitems.webp'
import _i_abyssnotable3 from './icons/abyssnotable3.webp'
import _i_breachnotable4 from './icons/breachnotable4.webp'
import _i_kiracnotable4 from './icons/kiracnotable4.webp'
import _i_watchstonenotable1 from './icons/watchstonenotable1.webp'
import _i_harvestnotable4 from './icons/harvestnotable4.webp'
import _i_deliriumnotable6 from './icons/deliriumnotable6.webp'
import _i_expeditionnotable2 from './icons/expeditionnotable2.webp'
import _i_expeditionnotable1 from './icons/expeditionnotable1.webp'
import _i_exceptionalitemsbodyarmour from './icons/exceptionalitemsbodyarmour.webp'
import _i_alvanotable2 from './icons/alvanotable2.webp'
import _i_ritualnotable2 from './icons/ritualnotable2.webp'
import _i_raremonstersnotable from './icons/raremonstersnotable.webp'
import _i_essencenotable3 from './icons/essencenotable3.webp'
import _i_ritualnotable4 from './icons/ritualnotable4.webp'
import _i_anarchynotable1 from './icons/anarchynotable1.webp'
import _i_deliriumnotable5 from './icons/deliriumnotable5.webp'
import _i_gemlinglevelallskillgems from './icons/gemlinglevelallskillgems.webp'
import _i_bossnotablespawnbeyondmonsters from './icons/bossnotablespawnbeyondmonsters.webp'
import _i_stonecircles from './icons/stonecircles.webp'
import _i_breachnotable3 from './icons/breachnotable3.webp'
import _i_wheelofdisablingbreach from './icons/wheelofdisablingbreach.webp'
import _i_abyssmonstersspawn from './icons/abyssmonstersspawn.webp'
import _i_deliriumnotable7 from './icons/deliriumnotable7.webp'
import _i_abyssnotable5 from './icons/abyssnotable5.webp'
import _i_ritualnotable1 from './icons/ritualnotable1.webp'
import _i_breachnotable7 from './icons/breachnotable7.webp'
import _i_bossnotablegrantmoreexperience from './icons/bossnotablegrantmoreexperience.webp'
import _i_breachnotable2 from './icons/breachnotable2.webp'
import _i_vividprimalwildwisps from './icons/vividprimalwildwisps.webp'
import _i_bossnotabledroprareritems from './icons/bossnotabledroprareritems.webp'
import _i_ritualnotable3 from './icons/ritualnotable3.webp'
import _i_abyssnotable from './icons/abyssnotable.webp'
import _i_deliriumnotable8 from './icons/deliriumnotable8.webp'
import _i_exceptionalitemshelmets from './icons/exceptionalitemshelmets.webp'
import _i_breachnotable6 from './icons/breachnotable6.webp'
import _i_abyssnotable6 from './icons/abyssnotable6.webp'
import _i_wheelofdisablingritual from './icons/wheelofdisablingritual.webp'
import _i_exceptionalitemsweaponsshields from './icons/exceptionalitemsweaponsshields.webp'
import _i_expeditionnotable4 from './icons/expeditionnotable4.webp'
import _i_extremearchaeology from './icons/extremearchaeology.webp'
import _i_breachnotable1 from './icons/breachnotable1.webp'
import _i_abyssto4 from './icons/abyssto4.webp'
import _i_deliriumnotable4 from './icons/deliriumnotable4.webp'
import _i_ritual from './icons/ritual.webp'
import _i_deliriumnotable1 from './icons/deliriumnotable1.webp'
import _i_ritualnotable from './icons/ritualnotable.webp'
import _i_deliriumnotable2 from './icons/deliriumnotable2.webp'
import _i_breachnotable8 from './icons/breachnotable8.webp'
import _i_breachnotable5 from './icons/breachnotable5.webp'
import _i_abyssnotable2 from './icons/abyssnotable2.webp'
import _i_bossnotabledropmorewaystone from './icons/bossnotabledropmorewaystone.webp'
import _i_masteryblank from './icons/masteryblank.webp'
import _i_forestbiome from './icons/forestbiome.webp'
import _i_streamofconsciousnesskeystone from './icons/streamofconsciousnesskeystone.webp'
import _i_breachbossclaspedhands from './icons/breachbossclaspedhands.webp'
import _i_citybiome from './icons/citybiome.webp'
import _i_waterbiome from './icons/waterbiome.webp'
import _i_swampbiome from './icons/swampbiome.webp'
import _i_blood2 from './icons/blood2.webp'
import _i_desertbiome from './icons/desertbiome.webp'
import _i_gemlingskillsadditionalsupport from './icons/gemlingskillsadditionalsupport.webp'
import _i_expeditionspawnmissinglife from './icons/expeditionspawnmissinglife.webp'
import _i_rarebreachmonsterblessing from './icons/rarebreachmonsterblessing.webp'
import _i_mountainbiome from './icons/mountainbiome.webp'
import _i_ritualreducedcostdeferrewards from './icons/ritualreducedcostdeferrewards.webp'
import _i_grassbiome from './icons/grassbiome.webp'
import _i_expeditiondannig from './icons/expeditiondannig.webp'
import _i_ritualreducererollcost from './icons/ritualreducererollcost.webp'
import _i_mapsadditionalbreaches from './icons/mapsadditionalbreaches.webp'
import _i_ritualchancebloodfilledvessel from './icons/ritualchancebloodfilledvessel.webp'
import _i_deliriumnode1 from './icons/deliriumnode1.webp'
import _i_swampbiomenode from './icons/swampbiomenode.webp'
import _i_shrinesnode from './icons/shrinesnode.webp'
import _i_breachnode2 from './icons/breachnode2.webp'
import _i_stonecirclesnode from './icons/stonecirclesnode.webp'
import _i_itemquantityandrarity from './icons/itemquantityandrarity.webp'
import _i_bossmapdrops from './icons/bossmapdrops.webp'
import _i_atlassabyssalnode from './icons/atlassabyssalnode.webp'
import _i_essencenode1 from './icons/essencenode1.webp'
import _i_breachnodechaos from './icons/breachnodechaos.webp'
import _i_azmerispiritsnode from './icons/azmerispiritsnode.webp'
import _i_expeditionnode1 from './icons/expeditionnode1.webp'
import _i_ritualnode1 from './icons/ritualnode1.webp'
import _i_hybridshrineazmerispirit from './icons/hybridshrineazmerispirit.webp'
import _i_forestbiomenode from './icons/forestbiomenode.webp'
import _i_alvanode2 from './icons/alvanode2.webp'
import _i_hybridstrongboxazmerispirit from './icons/hybridstrongboxazmerispirit.webp'
import _i_citybiomenode from './icons/citybiomenode.webp'
import _i_desertbiomenode from './icons/desertbiomenode.webp'
import _i_modifiertier from './icons/modifiertier.webp'
import _i_alvanode from './icons/alvanode.webp'
import _i_grassbiomenode from './icons/grassbiomenode.webp'
import _i_waterbiomenode from './icons/waterbiomenode.webp'
import _i_hybridessencerogueexile from './icons/hybridessencerogueexile.webp'
import _i_hybridstrongboxshrines from './icons/hybridstrongboxshrines.webp'
import _i_strongboxnode1 from './icons/strongboxnode1.webp'
import _i_mountainbiomenode from './icons/mountainbiomenode.webp'
import _i_hybridessencestonecircle from './icons/hybridessencestonecircle.webp'
import _i_hybridrogueexilestonecircle from './icons/hybridrogueexilestonecircle.webp'
import _i_lightningdamagenode from './icons/lightningdamagenode.webp'
import _s0 from './sprite0.webp'
import _s1 from './sprite1.webp'
import _s2 from './sprite2.webp'
import _s3 from './sprite3.webp'
import _s4 from './sprite4.webp'
import _s5 from './sprite5.webp'

export const ICON_URLS: Record<string, string> = {
  atlasmasterygeneric: _i_atlasmasterygeneric,
  atlasmasteryessence: _i_atlasmasteryessence,
  atlasmasterybiome: _i_atlasmasterybiome,
  atlasmasterystonecircles: _i_atlasmasterystonecircles,
  atlasmasteryrogueexile: _i_atlasmasteryrogueexile,
  atlasmasterystrongbox: _i_atlasmasterystrongbox,
  atlasmasteryazmerispirits: _i_atlasmasteryazmerispirits,
  atlasmasteryshrine: _i_atlasmasteryshrine,
  expeditionnotable5: _i_expeditionnotable5,
  expeditionnotable3: _i_expeditionnotable3,
  strongboxnotable1: _i_strongboxnotable1,
  abyssnotable1: _i_abyssnotable1,
  disablingmasteralva: _i_disablingmasteralva,
  anarchynotable3: _i_anarchynotable3,
  raremonstersnode: _i_raremonstersnode,
  alvanotable4: _i_alvanotable4,
  deliriumnotable3: _i_deliriumnotable3,
  strongboxnotable3: _i_strongboxnotable3,
  exceptionalitemsboots: _i_exceptionalitemsboots,
  abyssnotable4: _i_abyssnotable4,
  abysscrack: _i_abysscrack,
  shrines: _i_shrines,
  exceptionalitemsgloves: _i_exceptionalitemsgloves,
  alvanotable3: _i_alvanotable3,
  alvanotable1: _i_alvanotable1,
  bossnotabledropmoreitems: _i_bossnotabledropmoreitems,
  abyssnotable3: _i_abyssnotable3,
  breachnotable4: _i_breachnotable4,
  kiracnotable4: _i_kiracnotable4,
  watchstonenotable1: _i_watchstonenotable1,
  harvestnotable4: _i_harvestnotable4,
  deliriumnotable6: _i_deliriumnotable6,
  expeditionnotable2: _i_expeditionnotable2,
  expeditionnotable1: _i_expeditionnotable1,
  exceptionalitemsbodyarmour: _i_exceptionalitemsbodyarmour,
  alvanotable2: _i_alvanotable2,
  ritualnotable2: _i_ritualnotable2,
  raremonstersnotable: _i_raremonstersnotable,
  essencenotable3: _i_essencenotable3,
  ritualnotable4: _i_ritualnotable4,
  anarchynotable1: _i_anarchynotable1,
  deliriumnotable5: _i_deliriumnotable5,
  gemlinglevelallskillgems: _i_gemlinglevelallskillgems,
  bossnotablespawnbeyondmonsters: _i_bossnotablespawnbeyondmonsters,
  stonecircles: _i_stonecircles,
  breachnotable3: _i_breachnotable3,
  wheelofdisablingbreach: _i_wheelofdisablingbreach,
  abyssmonstersspawn: _i_abyssmonstersspawn,
  deliriumnotable7: _i_deliriumnotable7,
  abyssnotable5: _i_abyssnotable5,
  ritualnotable1: _i_ritualnotable1,
  breachnotable7: _i_breachnotable7,
  bossnotablegrantmoreexperience: _i_bossnotablegrantmoreexperience,
  breachnotable2: _i_breachnotable2,
  vividprimalwildwisps: _i_vividprimalwildwisps,
  bossnotabledroprareritems: _i_bossnotabledroprareritems,
  ritualnotable3: _i_ritualnotable3,
  abyssnotable: _i_abyssnotable,
  deliriumnotable8: _i_deliriumnotable8,
  exceptionalitemshelmets: _i_exceptionalitemshelmets,
  breachnotable6: _i_breachnotable6,
  abyssnotable6: _i_abyssnotable6,
  wheelofdisablingritual: _i_wheelofdisablingritual,
  exceptionalitemsweaponsshields: _i_exceptionalitemsweaponsshields,
  expeditionnotable4: _i_expeditionnotable4,
  extremearchaeology: _i_extremearchaeology,
  breachnotable1: _i_breachnotable1,
  abyssto4: _i_abyssto4,
  deliriumnotable4: _i_deliriumnotable4,
  ritual: _i_ritual,
  deliriumnotable1: _i_deliriumnotable1,
  ritualnotable: _i_ritualnotable,
  deliriumnotable2: _i_deliriumnotable2,
  breachnotable8: _i_breachnotable8,
  breachnotable5: _i_breachnotable5,
  abyssnotable2: _i_abyssnotable2,
  bossnotabledropmorewaystone: _i_bossnotabledropmorewaystone,
  masteryblank: _i_masteryblank,
  forestbiome: _i_forestbiome,
  streamofconsciousnesskeystone: _i_streamofconsciousnesskeystone,
  breachbossclaspedhands: _i_breachbossclaspedhands,
  citybiome: _i_citybiome,
  waterbiome: _i_waterbiome,
  swampbiome: _i_swampbiome,
  blood2: _i_blood2,
  desertbiome: _i_desertbiome,
  gemlingskillsadditionalsupport: _i_gemlingskillsadditionalsupport,
  expeditionspawnmissinglife: _i_expeditionspawnmissinglife,
  rarebreachmonsterblessing: _i_rarebreachmonsterblessing,
  mountainbiome: _i_mountainbiome,
  ritualreducedcostdeferrewards: _i_ritualreducedcostdeferrewards,
  grassbiome: _i_grassbiome,
  expeditiondannig: _i_expeditiondannig,
  ritualreducererollcost: _i_ritualreducererollcost,
  mapsadditionalbreaches: _i_mapsadditionalbreaches,
  ritualchancebloodfilledvessel: _i_ritualchancebloodfilledvessel,
  deliriumnode1: _i_deliriumnode1,
  swampbiomenode: _i_swampbiomenode,
  shrinesnode: _i_shrinesnode,
  breachnode2: _i_breachnode2,
  stonecirclesnode: _i_stonecirclesnode,
  itemquantityandrarity: _i_itemquantityandrarity,
  bossmapdrops: _i_bossmapdrops,
  atlassabyssalnode: _i_atlassabyssalnode,
  essencenode1: _i_essencenode1,
  breachnodechaos: _i_breachnodechaos,
  azmerispiritsnode: _i_azmerispiritsnode,
  expeditionnode1: _i_expeditionnode1,
  ritualnode1: _i_ritualnode1,
  hybridshrineazmerispirit: _i_hybridshrineazmerispirit,
  forestbiomenode: _i_forestbiomenode,
  alvanode2: _i_alvanode2,
  hybridstrongboxazmerispirit: _i_hybridstrongboxazmerispirit,
  citybiomenode: _i_citybiomenode,
  desertbiomenode: _i_desertbiomenode,
  modifiertier: _i_modifiertier,
  alvanode: _i_alvanode,
  grassbiomenode: _i_grassbiomenode,
  waterbiomenode: _i_waterbiomenode,
  hybridessencerogueexile: _i_hybridessencerogueexile,
  hybridstrongboxshrines: _i_hybridstrongboxshrines,
  strongboxnode1: _i_strongboxnode1,
  mountainbiomenode: _i_mountainbiomenode,
  hybridessencestonecircle: _i_hybridessencestonecircle,
  hybridrogueexilestonecircle: _i_hybridrogueexilestonecircle,
  lightningdamagenode: _i_lightningdamagenode,
}

/** base -> [sheet, x, y, w, h, scale]: sheet-pixel crop; draw size is px / scale. */
export const ICON_RECTS: Record<string, [number, number, number, number, number, number]> = {
  atlasmasterygeneric: [5, 2, 2, 128, 128, 2],
  atlasmasteryessence: [5, 134, 2, 128, 128, 2],
  atlasmasterybiome: [5, 266, 2, 128, 128, 2],
  atlasmasterystonecircles: [5, 398, 2, 128, 128, 2],
  atlasmasteryrogueexile: [5, 530, 2, 128, 128, 2],
  atlasmasterystrongbox: [5, 662, 2, 128, 128, 2],
  atlasmasteryazmerispirits: [5, 794, 2, 128, 128, 2],
  atlasmasteryshrine: [5, 2, 134, 128, 128, 2],
  expeditionnotable5: [5, 134, 134, 88, 88, 2],
  expeditionnotable3: [5, 226, 134, 88, 88, 2],
  strongboxnotable1: [5, 318, 134, 88, 88, 2],
  abyssnotable1: [5, 410, 134, 88, 88, 2],
  disablingmasteralva: [5, 502, 134, 88, 88, 2],
  anarchynotable3: [5, 594, 134, 88, 88, 2],
  raremonstersnode: [5, 686, 134, 88, 88, 2],
  alvanotable4: [5, 778, 134, 88, 88, 2],
  deliriumnotable3: [5, 870, 134, 88, 88, 2],
  strongboxnotable3: [5, 2, 266, 88, 88, 2],
  exceptionalitemsboots: [5, 94, 266, 88, 88, 2],
  abyssnotable4: [5, 186, 266, 88, 88, 2],
  abysscrack: [5, 278, 266, 88, 88, 2],
  shrines: [5, 370, 266, 88, 88, 2],
  exceptionalitemsgloves: [5, 462, 266, 88, 88, 2],
  alvanotable3: [5, 554, 266, 88, 88, 2],
  alvanotable1: [5, 646, 266, 88, 88, 2],
  bossnotabledropmoreitems: [5, 738, 266, 88, 88, 2],
  abyssnotable3: [5, 830, 266, 88, 88, 2],
  breachnotable4: [5, 922, 266, 88, 88, 2],
  kiracnotable4: [5, 2, 358, 88, 88, 2],
  watchstonenotable1: [5, 94, 358, 88, 88, 2],
  harvestnotable4: [5, 186, 358, 88, 88, 2],
  deliriumnotable6: [5, 278, 358, 88, 88, 2],
  expeditionnotable2: [5, 370, 358, 88, 88, 2],
  expeditionnotable1: [5, 462, 358, 88, 88, 2],
  exceptionalitemsbodyarmour: [5, 554, 358, 88, 88, 2],
  alvanotable2: [5, 646, 358, 88, 88, 2],
  ritualnotable2: [5, 738, 358, 88, 88, 2],
  raremonstersnotable: [5, 830, 358, 88, 88, 2],
  essencenotable3: [5, 922, 358, 88, 88, 2],
  ritualnotable4: [5, 2, 450, 88, 88, 2],
  anarchynotable1: [5, 94, 450, 88, 88, 2],
  deliriumnotable5: [5, 186, 450, 88, 88, 2],
  gemlinglevelallskillgems: [5, 278, 450, 88, 88, 2],
  bossnotablespawnbeyondmonsters: [5, 370, 450, 88, 88, 2],
  stonecircles: [5, 462, 450, 88, 88, 2],
  breachnotable3: [5, 554, 450, 88, 88, 2],
  wheelofdisablingbreach: [5, 646, 450, 88, 88, 2],
  abyssmonstersspawn: [5, 738, 450, 88, 88, 2],
  deliriumnotable7: [5, 830, 450, 88, 88, 2],
  abyssnotable5: [5, 922, 450, 88, 88, 2],
  ritualnotable1: [5, 2, 542, 88, 88, 2],
  breachnotable7: [5, 94, 542, 88, 88, 2],
  bossnotablegrantmoreexperience: [5, 186, 542, 88, 88, 2],
  breachnotable2: [5, 278, 542, 88, 88, 2],
  vividprimalwildwisps: [5, 370, 542, 88, 88, 2],
  bossnotabledroprareritems: [5, 462, 542, 88, 88, 2],
  ritualnotable3: [5, 554, 542, 88, 88, 2],
  abyssnotable: [5, 646, 542, 88, 88, 2],
  deliriumnotable8: [5, 738, 542, 88, 88, 2],
  exceptionalitemshelmets: [5, 830, 542, 88, 88, 2],
  breachnotable6: [5, 922, 542, 88, 88, 2],
  abyssnotable6: [5, 2, 634, 88, 88, 2],
  wheelofdisablingritual: [5, 94, 634, 88, 88, 2],
  exceptionalitemsweaponsshields: [5, 186, 634, 88, 88, 2],
  expeditionnotable4: [5, 278, 634, 88, 88, 2],
  extremearchaeology: [5, 370, 634, 88, 88, 2],
  breachnotable1: [5, 462, 634, 88, 88, 2],
  abyssto4: [5, 554, 634, 88, 88, 2],
  deliriumnotable4: [5, 646, 634, 88, 88, 2],
  ritual: [5, 738, 634, 88, 88, 2],
  deliriumnotable1: [5, 830, 634, 88, 88, 2],
  ritualnotable: [5, 922, 634, 88, 88, 2],
  deliriumnotable2: [5, 2, 726, 88, 88, 2],
  breachnotable8: [5, 94, 726, 88, 88, 2],
  breachnotable5: [5, 186, 726, 88, 88, 2],
  abyssnotable2: [5, 278, 726, 88, 88, 2],
  bossnotabledropmorewaystone: [5, 370, 726, 88, 88, 2],
  masteryblank: [5, 462, 726, 86, 86, 2],
  forestbiome: [5, 552, 726, 64, 64, 2],
  streamofconsciousnesskeystone: [5, 620, 726, 64, 64, 2],
  breachbossclaspedhands: [5, 688, 726, 64, 64, 2],
  citybiome: [5, 756, 726, 64, 64, 2],
  waterbiome: [5, 824, 726, 64, 64, 2],
  swampbiome: [5, 892, 726, 64, 64, 2],
  blood2: [5, 2, 818, 64, 64, 2],
  desertbiome: [5, 70, 818, 64, 64, 2],
  gemlingskillsadditionalsupport: [5, 138, 818, 64, 64, 2],
  expeditionspawnmissinglife: [5, 206, 818, 64, 64, 2],
  rarebreachmonsterblessing: [5, 274, 818, 64, 64, 2],
  mountainbiome: [5, 342, 818, 64, 64, 2],
  ritualreducedcostdeferrewards: [5, 410, 818, 64, 64, 2],
  grassbiome: [5, 478, 818, 64, 64, 2],
  expeditiondannig: [5, 546, 818, 64, 64, 2],
  ritualreducererollcost: [5, 614, 818, 64, 64, 2],
  mapsadditionalbreaches: [5, 682, 818, 64, 64, 2],
  ritualchancebloodfilledvessel: [5, 750, 818, 64, 64, 2],
  deliriumnode1: [5, 194, 886, 44, 44, 2],
  swampbiomenode: [5, 242, 886, 44, 44, 2],
  shrinesnode: [5, 290, 886, 44, 44, 2],
  breachnode2: [5, 338, 886, 44, 44, 2],
  stonecirclesnode: [5, 386, 886, 44, 44, 2],
  itemquantityandrarity: [5, 434, 886, 44, 44, 2],
  bossmapdrops: [5, 482, 886, 44, 44, 2],
  atlassabyssalnode: [5, 530, 886, 44, 44, 2],
  essencenode1: [5, 578, 886, 44, 44, 2],
  breachnodechaos: [5, 626, 886, 44, 44, 2],
  azmerispiritsnode: [5, 674, 886, 44, 44, 2],
  expeditionnode1: [5, 722, 886, 44, 44, 2],
  ritualnode1: [5, 770, 886, 44, 44, 2],
  hybridshrineazmerispirit: [5, 818, 886, 44, 44, 2],
  forestbiomenode: [5, 866, 886, 44, 44, 2],
  alvanode2: [5, 914, 886, 44, 44, 2],
  hybridstrongboxazmerispirit: [5, 962, 886, 44, 44, 2],
  citybiomenode: [5, 2, 951, 44, 44, 2],
  desertbiomenode: [5, 50, 951, 44, 44, 2],
  modifiertier: [5, 98, 951, 44, 44, 2],
  alvanode: [5, 146, 951, 44, 44, 2],
  grassbiomenode: [5, 194, 951, 44, 44, 2],
  waterbiomenode: [5, 242, 951, 44, 44, 2],
  hybridessencerogueexile: [5, 290, 951, 44, 44, 2],
  hybridstrongboxshrines: [5, 338, 951, 44, 44, 2],
  strongboxnode1: [5, 386, 951, 44, 44, 2],
  mountainbiomenode: [5, 434, 951, 44, 44, 2],
  hybridessencestonecircle: [5, 482, 951, 44, 44, 2],
  hybridrogueexilestonecircle: [5, 530, 951, 44, 44, 2],
  lightningdamagenode: [5, 578, 951, 32, 32, 2],
}

export const SPRITES: Record<number, string> = {
  0: _s0,
  1: _s1,
  2: _s2,
  3: _s3,
  4: _s4,
  5: _s5,
}

export const SHEET_SIZES: Record<number, [number, number]> = {
  0: [512, 256],
  1: [2048, 2048],
  2: [1024, 1024],
  3: [1024, 1024],
  4: [2048, 1024],
  5: [1024, 1024],
}

/** frame/starting-point name -> [sheet, x, y, w, h, scale]. */
export const FRAMES: Record<string, [number, number, number, number, number, number]> = {
  keystoneframeactive: [0, 143, 2, 109, 111, 2],
  keystoneframenormal: [0, 256, 2, 109, 111, 2],
  notableframeactive: [0, 369, 2, 75, 75, 2],
  notableframenormal: [0, 2, 143, 75, 75, 2],
  startingpointbreachactive: [5, 818, 818, 60, 61, 2],
  startingpointexpeditionactive: [5, 882, 818, 60, 61, 2],
  startingpointdeliriumactive: [5, 946, 818, 60, 61, 2],
  startingpointritualactive: [5, 2, 886, 60, 61, 2],
  startingpointabyssactive: [5, 66, 886, 60, 61, 2],
  startingpointincursionactive: [5, 130, 886, 60, 61, 2],
}
